const {
    secure,
    sessionTTL,
    conf,
    oauth2,
} = require(`./_utils.js`);

module.exports = {
    id: "heretic",
    secret: secure.secret,
    hashMethod: "argon2",
    server: {
        ip: "0.0.0.0",
        port: 3001,
        static: true,
        trustProxy: true,
        ignoreTrailingSlash: true,
        ...conf.server,
    },
    auth: {
        admin: false,
        signIn: false,
        signUp: false,
        ...conf.auth,
    },
    mongo: {
        enabled: false,
        url: "mongodb://0.0.0.0:27017",
        dbName: "heretic",
        options: {
            connectTimeoutMS: 5000,
        },
        ...conf.mongo,
    },
    redis: {
        enabled: false,
        host: "127.0.0.1",
        port: 6379,
        connectTimeout: 500,
        maxRetriesPerRequest: 1,
        ...conf.redis,
    },
    email: {
        enabled: false,
        from: "noreply@hereticjs.org",
        admin: "admin@hereticjs.org",
        config: {},
    },
    webSockets: {
        enabled: false,
        url: "ws://127.0.0.1:3001/ws",
        options: {
            maxPayload: 1048576,
        },
        ...conf.webSockets,
    },
    token: {
        expiresIn: sessionTTL,
        ip: false,
        ...conf.token,
    },
    passwordPolicy: {
        minLength: 8,
        maxLength: null,
        minGroups: 2,
        uppercase: true,
        lowercase: true,
        numbers: true,
        special: true,
    },
    oauth2: [
        ...oauth2,
        ...(conf.oauth2 || []),
    ],
    cookieOptions: {
        expires: sessionTTL,
        path: "/",
        domain: "",
        secure: null,
        sameSite: null,
        userCheck: true,
        ...conf.cookieOptions,
    },
    log: {
        level: "info",
        ...conf.log,
    },
    rateLimit: {
        enabled: false,
        ban: false,
        global: {
            max: 500,
            ban: 1000,
            timeWindow: 10000,
            nameSpace: "heretic-rate-limit-",
        },
        whiteList: [],
        blackList: [],
        addHeaders: {
            "x-ratelimit-limit": true,
            "x-ratelimit-remaining": true,
            "x-ratelimit-reset": true,
            "retry-after": true,
        },
        ...conf.rateLimit,
    },
    directories: {
        tmp: null,
        files: "files",
        ...conf.directories,
    },
    collections: {
        users: "users",
        files: "files",
        counters: "counters",
        history: "history",
        groups: "groups",
        events: "events",
        geoNetworks: "geoNetworks",
        geoCountries: "geoCountries",
        geoCities: "geoCities",
        version: "version",
        sessions: "sessions",
        activation: "activation",
        captcha: "captcha",
        jobs: "jobs",
        content: "content",
        ...conf.collections,
    },
    routes: {
        admin: "/admin",
        signInAdmin: "/admin/signIn",
        signIn: "/signIn",
        signOutAdmin: "/admin/signOut",
        signOut: "/signOut",
        account: "/account",
        signUp: "/signUp",
        restorePassword: "/restorePassword",
        privacyPolicy: "/privacy/site",
        privacyCookies: "/privacy/cookies",
        ...conf.routes,
    },
    buildOptions: {
        productionCompress: false,
        ...conf.buildOptions,
    },
    test: {
        headless: true,
        executablePath: "auto",
        args: ["--window-size=1920,1080", "--no-sandbox"],
        defaultViewport: null,
        devtools: true,
        ...conf.test,
    },
    heretic: {
        zipball: "http://github.com/hereticjsorg/heretic/zipball/master/",
        packageJson: "https://raw.githubusercontent.com/hereticjsorg/heretic/master/package.json",
        darkModeEnabled: true,
        restartCommand: "pm2 restart [id]",
        ...conf.heretic,
    },
    ...conf.system,
    sessionTTL,
    demo: true,
};
